### ISSUE TITLE
Checklist for Doing a Public, Coordinated Schlesi Testnet

### ISSUE THREAD

**Issue by rauljordan** [goerli/medalla#2]
Hi all,

As this multiclient effort matures, it's important for teams to be on the same page regarding what is needed before we can do a public, coordinated testnet launch like the @prysmaticlabs' topaz testnet [here](https://medium.com/prysmatic-labs/introducing-topaz-testnet-8e8a4e00a700). Here are some tentative milestones before a lighthouse+prysm public testnet announcement should occur:
- [ ] No skipping or minimal finality delays for N epochs
- [ ] Testnet resilience to recover under N epochs without finality
- [ ] Initial chain sync stress tested
- [ ] Stress testing N number of validators, where N in (16k, 50k, 100k)
- [ ] Slashable events occurring and successfully caught by [slasher](https://github.com/prysmaticlabs/prysm/tree/master/slasher)
- [ ] Major node panics/crashes resolved across both clients
- [ ] High chain participation > 97% as well as good profitability metrics for validators (less critical as can be improved over time)

Thoughts?

**Comment by prestonvanloon** [comment]
Please add validator activation and voluntary exits.

**Comment by q9f** [comment]
These points are looking sane. It still requires a lot of work for a long-term public multi-client testnet. Currently, Schlesi will probably either die or be reset every other week. Right now, it still requires a lot of patching and should mainly be used by client teams to nail down remaining issues.

Lighthouse is pretty good at supporting custom chain configurations, so it's easy to setup a couple of LH nodes with a Schlesi config. Unfortunately, there is no network config abstraction in Prysm that could be used currently. On my wish-list for Prysm would be either support for a custom network specification (yaml?) to override the default beaconChainConfig or a way to fully specify networks interally, i.e., having a `--chain topaz` and `--chain schlesi` flag. Could you add that to the list maybe?

Also, spec version is always a moving target and in case we would have to reset Schlesi or Topaz today, I would go for `v0.11.2` instead of `v0.12.0`. This would also allow other clients that implement v0.11.x to catch up with these networks soon.

A realistic timeline for a _public_ Schlesi launch would be >6 weeks at least, as I would carefully guess. I'm not sure what the timeline for v0.12.x looks like but I believe we will be still on v0.11.x in June. Correct me if I'm wrong.
